apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-checkout
  labels:
    account: checkout
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkout
spec:
  selector:
    matchLabels:
      app: checkout
  template:
    metadata:
      labels:
        app: checkout
        version: v1
    spec:
      serviceAccountName: app-checkout
      containers:
      - name: server
        image: mouhib19/microservices-checkoutservice:1.0.0-5
        imagePullPolicy: Always 
        ports:
        - containerPort: 5050
        env:
        - name: PORT
          value: "5050"
        - name: DISABLE_PROFILER
          value: "1"
        - name: PRODUCT_CATALOG_SERVICE_ADDR
          value: "productcatalogue:3550" 
        - name: SHIPPING_SERVICE_ADDR
          value: "shipping:50051" 
        - name: PAYMENT_SERVICE_ADDR
          value: "payment:50051" 
        - name: EMAIL_SERVICE_ADDR
          value: "email:8080" 
        - name: CURRENCY_SERVICE_ADDR
          value: "currency:7000" 
        - name: CART_SERVICE_ADDR
          value: "cart:7070"
        resources:
          limits:
            memory: "300Mi"
            cpu: "300m"
          requests:
            memory: "180Mi"
            cpu: "200m"
        readinessProbe:
          initialDelaySeconds: 20
          periodSeconds: 15
          grpc:
            port: 5050
        livenessProbe:
          initialDelaySeconds: 20
          periodSeconds: 15
          grpc:
            port: 5050
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000 
          runAsGroup: 1000
---
apiVersion: v1
kind: Service
metadata:
  name: checkout
  labels:
    app: checkout
    service: checkout
spec:
  type: ClusterIP
  selector:
    app: checkout
  ports:
  - name: grpc
    port: 5050
    targetPort: 5050
