apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-frontend
  labels:
    account: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-v1
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
        version: v1
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
    spec:
      serviceAccountName: app-frontend
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: server
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
          image: mouhib19/microservices-frontend:1.0.0-4
          imagePullPolicy: Always
          ports:
          - containerPort: 8080
          env:
          - name: PORT
            value: "8080"
          - name: PRODUCT_CATALOG_SERVICE_ADDR
            value: "productcatalogue:3550"
          - name: CURRENCY_SERVICE_ADDR
            value: "currency:7000"
          - name: CART_SERVICE_ADDR
            value: "cart:7070"
          - name: RECOMMENDATION_SERVICE_ADDR
            value: "recommendation:8080"
          - name: SHIPPING_SERVICE_ADDR
            value: "shipping:50051"
          - name: CHECKOUT_SERVICE_ADDR
            value: "checkout:5050"
          - name: AD_SERVICE_ADDR
            value: "adservice:9555"
          - name: ENABLE_PROFILER
            value: "0"
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
---

apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
    service: frontend
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
  - name: http
    port: 80
    targetPort: 8080
