apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-payment
  labels:
    account: payment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
spec:
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
        version: v1
    spec:
      serviceAccountName: app-payment
      containers:
      - name: server
        image: mouhib19/microservices-paymentservice:1.0.0-3
        imagePullPolicy: Always 
        ports:
        - containerPort: 50051
        env:
        - name: PORT
          value: "50051"
        - name: DISABLE_PROFILER
          value: "1"
        resources:
          limits:
            memory: "300Mi"
            cpu: "300m"
          requests:
            memory: "180Mi"
            cpu: "200m"
        readinessProbe:
          initialDelaySeconds: 20
          periodSeconds: 15
          grpc:
            port: 50051
        livenessProbe:
          initialDelaySeconds: 20
          periodSeconds: 15
          grpc:
            port: 50051
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000 
          runAsGroup: 1000
---
apiVersion: v1
kind: Service
metadata:
  name: payment
  labels:
    app: payment
    service: payment
spec:
  type: ClusterIP
  selector:
    app: payment
  ports:
  - name: grpc
    port: 50051
    targetPort: 50051
