apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-productcatalogue
  labels:
    account: productcatalogue
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: productcatalogue
spec:
  selector:
    matchLabels:
      app: productcatalogue
  template:
    metadata:
      labels:
        app: productcatalogue
        version: v1
    spec:
      serviceAccountName: app-productcatalogue
      containers:
      - name: server
        image: mouhib19/microservices-productcatalogservice:1.0.0-3
        imagePullPolicy: Always 
        ports:
        - containerPort: 3550
        env:
        - name: PORT
          value: "3550"
        - name: DISABLE_PROFILER
          value: "1"
        resources:
          limits:
            memory: "300Mi"
            cpu: "300m"
          requests:
            memory: "180Mi"
            cpu: "200m"
        readinessProbe:
          initialDelaySeconds: 20
          periodSeconds: 15
          grpc:
            port: 3550
        livenessProbe:
          initialDelaySeconds: 20
          periodSeconds: 15
          grpc:
            port: 3550
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000 
          runAsGroup: 1000
---
apiVersion: v1
kind: Service
metadata:
  name: productcatalogue
  labels:
    app: productcatalogue
    service: productcatalogue
spec:
  type: ClusterIP
  selector:
    app: productcatalogue
  ports:
  - name: grpc
    port: 3550
    targetPort: 3550
